# Generated by Django 4.1.3 on 2022-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLpaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orignal_url', models.CharField(max_length=200)),
                ('short_url', models.CharField(max_length=100)),
            ],
        ),
    ]
